# Generated by Django 4.2.3 on 2023-07-27 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Alternative name', max_length=64)),
                ('reference_ranking', models.IntegerField(blank=True, help_text='Alternative reference ranking', null=True)),
                ('ranking', models.IntegerField(help_text='Alternative ranking')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Criterion name', max_length=64)),
                ('gain', models.BooleanField(help_text='Criterion is the type of gain')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='User email', max_length=32, unique=True)),
                ('password', models.CharField(help_text='User password', max_length=32)),
                ('name', models.CharField(help_text='User first name', max_length=64)),
                ('surname', models.CharField(help_text='User last name', max_length=64)),
            ],
            options={
                'ordering': ('name', 'surname', 'email'),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project name', max_length=64)),
                ('description', models.CharField(help_text='Project description', max_length=256)),
                ('shareable', models.BooleanField(help_text='Project shareability')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='utagmsapi.user')),
            ],
            options={
                'ordering': ('name', 'user'),
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(help_text='Performance value')),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='utagmsapi.alternative')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='utagmsapi.criterion')),
            ],
            options={
                'ordering': ('criterion', 'alternative'),
            },
        ),
        migrations.CreateModel(
            name='HasseGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_down', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasse_graphs_down', to='utagmsapi.alternative')),
                ('alternative_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasse_graphs_up', to='utagmsapi.alternative')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasse_graphs', to='utagmsapi.project')),
            ],
            options={
                'ordering': ('project', 'alternative_up', 'alternative_down'),
            },
        ),
        migrations.CreateModel(
            name='CriterionFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinate', models.FloatField(help_text='Ordinate')),
                ('abscissa', models.FloatField(help_text='Abscissa')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_functions', to='utagmsapi.criterion')),
            ],
            options={
                'ordering': ('criterion',),
            },
        ),
        migrations.AddField(
            model_name='criterion',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='utagmsapi.project'),
        ),
        migrations.AddField(
            model_name='alternative',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='utagmsapi.project'),
        ),
    ]
