# Generated by Django 4.2.3 on 2023-12-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utagmsapi', '0003_preferenceintensity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inconsistency',
            name='type',
            field=models.CharField(choices=[('>', 'Preference'), ('>=', 'Weak preference'), ('=', 'Indifference'), ('position', 'Position'), ('intensity', 'Intensity')]),
        ),
    ]
