# Generated by Django 4.2.3 on 2023-08-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utagmsapi', '0004_alter_project_shareable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, help_text='Project description', max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='shareable',
            field=models.BooleanField(help_text='Project shareability'),
        ),
    ]
