# Generated by Django 4.2.3 on 2023-12-04 12:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utagmsapi', '0004_alter_inconsistency_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairwiseWinning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(help_text='In how many percent of cases is alternative_1 better than alternative_2?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alternative_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_winnings_1', to='utagmsapi.alternative')),
                ('alternative_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_winnings_2', to='utagmsapi.alternative')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('necessary', 'Necessary'), ('possible', 'Possible')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alternative_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_1', to='utagmsapi.alternative')),
                ('alternative_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_2', to='utagmsapi.alternative')),
            ],
            options={
                'ordering': ('category', 'alternative_1', 'alternative_2'),
            },
        ),
        migrations.RemoveField(
            model_name='acceptabilityindex',
            name='alternative_1',
        ),
        migrations.RemoveField(
            model_name='acceptabilityindex',
            name='alternative_2',
        ),
        migrations.RemoveField(
            model_name='acceptabilityindex',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='category',
            name='hasse_graph',
        ),
        migrations.AddField(
            model_name='acceptabilityindex',
            name='alternative',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='acceptability_indices', to='utagmsapi.alternative'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acceptabilityindex',
            name='percent',
            field=models.FloatField(default=0, help_text='How many percent of cases was the alternative in this position?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acceptabilityindex',
            name='position',
            field=models.IntegerField(default=0, help_text='Position of the index'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='has_results',
            field=models.BooleanField(default=False, help_text='Are results for this category calculated?'),
        ),
        migrations.AddField(
            model_name='inconsistency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inconsistency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Percentage',
        ),
        migrations.AddField(
            model_name='relation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='utagmsapi.category'),
        ),
        migrations.AddField(
            model_name='pairwisewinning',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_winnings', to='utagmsapi.category'),
        ),
    ]
