# Generated by Django 4.2.3 on 2023-12-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utagmsapi', '0005_pairwisewinning_relation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='extreme_best',
            field=models.IntegerField(default=0, help_text='Best possible position the alternative has'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ranking',
            name='extreme_worst',
            field=models.IntegerField(default=0, help_text='Worst possible position the alternative has'),
            preserve_default=False,
        ),
    ]
