# Generated by Django 4.2.3 on 2023-08-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utagmsapi', '0005_alter_project_description_alter_project_shareable'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='linear_segments',
            field=models.IntegerField(default=0, help_text='How many linear segments does criterion have'),
            preserve_default=False,
        ),
    ]
