# Generated by Django 4.2.3 on 2023-09-23 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utagmsapi', '0006_criterion_linear_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='weight',
            field=models.IntegerField(default=1, help_text='Weight of the criterion', validators=[django.core.validators.MinValueValidator(1, 'Weight must be at least 1')]),
        ),
    ]
