# Generated by Django 4.2.3 on 2023-09-25 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utagmsapi', '0007_criterion_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='weight',
            field=models.FloatField(default=0.0, help_text='Weight of the criterion', validators=[django.core.validators.MinValueValidator(0.0, 'Weight must be at least 0'), django.core.validators.MaxValueValidator(1.0, 'Weight must be at most 1')]),
        ),
    ]
