# Generated by Django 4.2.3 on 2024-01-10 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utagmsapi', '0008_rename_percentage_pairwisewinning_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='samples',
            field=models.IntegerField(default=100, help_text='How many samples will be calculated for this category?', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
