# Generated by Django 4.2.3 on 2023-09-30 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utagmsapi', '0008_alter_criterion_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceIntensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alternative_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_intensities_1', to='utagmsapi.alternative')),
                ('alternative_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_intensities_2', to='utagmsapi.alternative')),
                ('alternative_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_intensities_3', to='utagmsapi.alternative')),
                ('alternative_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_intensities_4', to='utagmsapi.alternative')),
                ('criterion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preference_intensities', to='utagmsapi.criterion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_intensities', to='utagmsapi.project')),
            ],
            options={
                'ordering': ('project', 'criterion'),
            },
        ),
    ]
