# Generated by Django 4.2.3 on 2023-10-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utagmsapi', '0009_preferenceintensity'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hasse_graph',
            field=models.JSONField(help_text="Graph that represents necessary relations between project's alternatives", null=True),
        ),
    ]
