# Generated by Django 4.2.3 on 2023-10-18 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utagmsapi', '0010_project_hasse_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pairwise_mode',
            field=models.BooleanField(default=False, help_text="Set to 'True' if Pairwise Comparisons will be used, or 'False' if Reference Ranking is preferred."),
        ),
        migrations.CreateModel(
            name='PairwiseComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('preference', 'Preference'), ('indifference', 'Indifference')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alternative_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_comparisons_1', to='utagmsapi.alternative')),
                ('alternative_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_comparisons_2', to='utagmsapi.alternative')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_comparisons', to='utagmsapi.project')),
            ],
        ),
    ]
