# Generated by Django 4.2.3 on 2023-10-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utagmsapi', '0011_project_pairwise_mode_pairwisecomparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='highest_position',
            field=models.IntegerField(blank=True, help_text='Highest position the alternative can have in the final ranking', null=True),
        ),
        migrations.AddField(
            model_name='alternative',
            name='lowest_position',
            field=models.IntegerField(blank=True, help_text='Lowest position the alternative can have in the final ranking', null=True),
        ),
    ]
