# Generated by Django 4.2.3 on 2023-10-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utagmsapi', '0012_alternative_best_position_alternative_worst_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='ranking_value',
            field=models.FloatField(default=0.0, help_text="Alternative's final value in the ranking"),
        ),
    ]
