# Generated by Django 4.2.3 on 2023-10-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utagmsapi', '0013_alternative_ranking_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CriterionFunction',
            new_name='CriterionFunctionPoint',
        ),
        migrations.DeleteModel(
            name='HasseGraph',
        ),
    ]
