# Generated by Django 4.2.3 on 2023-11-01 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utagmsapi', '0014_rename_criterionfunction_criterionfunctionpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=64)),
                ('color', models.CharField(help_text='Color of the category', max_length=15)),
                ('active', models.BooleanField(default=True, help_text='Should the category be used in calculating results?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='utagmsapi.project')),
            ],
        ),
        migrations.AlterField(
            model_name='criterionfunctionpoint',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_function_points', to='utagmsapi.criterion'),
        ),
        migrations.CreateModel(
            name='CriterionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_categories', to='utagmsapi.category')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_categories', to='utagmsapi.criterion')),
            ],
            options={
                'ordering': ('category',),
            },
        ),
    ]
