version: '3.9'

services:
  uta-gms-django:
    container_name: uta_gms_django
    build:
      context: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    env_file: .env
    volumes:
      - .:/app